// scripts/generateScenes.js
const fs = require("fs");
const path = require("path");
const { Configuration, OpenAIApi } = require("openai");

const whisperPath = path.join(__dirname, "../temp/whisper.json");
const outputPath = path.join(__dirname, "../temp/scenePrompts.json");

const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(config);

async function generateScenesFromWhisper() {
  if (!fs.existsSync(whisperPath)) {
    throw new Error("Missing whisper.json");
  }

  const whisper = JSON.parse(fs.readFileSync(whisperPath, "utf-8"));
  const text = whisper.text;

  const systemPrompt = `
You are a cinematic scene director. Given a poetic whisper text, generate a list of 6 to 10 highly visual, immersive, short scene descriptions that could be generated by AI video tools like RunwayML or Pika.
Each scene must be between 4 and 6 seconds long.
Focus on mood, atmosphere, and cinematic language.
Scenes should be diverse and flow like a visual poem.
Do not repeat words or structure.

Respond ONLY with a JSON array of strings.
  `.trim();

  const response = await openai.createChatCompletion({
    model: "gpt-4",
    temperature: 0.9,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: text },
    ],
  });

  const raw = response.data.choices[0].message.content.trim();

  try {
    const sceneList = JSON.parse(raw);
    fs.writeFileSync(outputPath, JSON.stringify(sceneList, null, 2));
    console.log("✅ Scene prompts saved to:", outputPath);
  } catch (err) {
    console.error("❌ Failed to parse scene list:", raw);
    throw err;
  }
}

generateScenesFromWhisper();
