const { google } = require('googleapis');
const fs = require('fs');

module.exports.uploadToYouTube = async (videoPath, whisper) => {
  const oauth2Client = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET,
    'urn:ietf:wg:oauth:2.0:oob' // or your redirect URI
  );

  oauth2Client.setCredentials({
    refresh_token: process.env.YOUTUBE_REFRESH_TOKEN
  });

  const youtube = google.youtube({
    version: 'v3',
    auth: oauth2Client,
  });

  const res = await youtube.videos.insert({
    part: 'snippet,status',
    requestBody: {
      snippet: {
        title: whisper.title || 'Zen Whisper Upload',
        description: whisper.body || 'Generated by Zen Whisper Agent',
        tags: ['Zen', 'Whisper', 'Pasaguthi'],
      },
      status: {
        privacyStatus: 'unlisted', // or 'public'
      },
    },
    media: {
      body: fs.createReadStream(videoPath),
    },
  });

  console.log(`🎥 YouTube Video URL: https://youtu.be/${res.data.id}`);
  return `https://youtu.be/${res.data.id}`;
};
